# Generated by Django 6.0 on 2025-12-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwebUI', '0002_alter_contactsubmission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
