# Generated by Django 6.0 on 2025-12-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpost',
            name='report',
            field=models.ImageField(upload_to='medical_reports/'),
        ),
    ]
